reload_config_on_epoch: True
shutdown_secs: -1
cam_params: [277.13, 289.71, 159.5, 119.5] # fx,fy,cx,cy
num_primitives: 13
device: /device:gpu:0
vert_padding: [40,40]
horiz_padding: [0,0]
num_classes: 14
image_min_dim: 320
image_max_dim: 320

rpn_train_anchors_per_image: 49 # 7^2
rpn_anchor_scales: [16,32,64,128,160]
train_rois_per_image: 64

use_depth: true
use_normals: true
squish_inputs: false
rescale_rgb_to_unit: true

# object segmentation / mask
enable_segmentation_extension: true
seg:
  embedding_layers: [64,64]
  segment_layers: [64,64]

# input for loss functions
enable_primitive_extension: false
pose:
  trans_layers: [[],[]]
  rot_layers: []

use_roi_align_v2: false

detection_min_confidence: 0.65
detection_nms_threshold: 0.25

# Model configuration
use_previous_model: True
#excluded_weights: ['mrcnn_bbox_fc','mrcnn_class_logits','mrcnn_mask']
excluded_weights: []

# runtime parameters
# to be filled 
tag: "parts-scratch-nosquish"
rand: null
dataset: null

# Comet info
project_name: "PartNet"
comet_api_key: "B1xas0idw9x50yr8xk7JReNec"
description: "Basic network for initial experimentation with part-based learning."

train:
  model: "${tag}_mrcnn"
  model_name: "${train.model}_ep{epoch:04d}_{val_loss:.5f}.h5"
  state_name: "${tag}_mrcnn"
  train_val_test_split: [0.9,0.01,0.09]
  initial_epoch: 0
  num_visits: 1
  num_epochs: 100
  random_seed: 11521271
  stopping_patience: 20
  gpu_count: 1
  images_per_gpu: 4
  gradient_clip_norm: 5.0
  use_mini_mask: false
  learning_rate: 0.0001
  schedule_factor: 0.95
  learning_momentum: 0.9
  weight_decay: 0.00001

paths:
  base: "/data"
  out_base: "mkdir://${paths.base}/part-rcnn"
  log_base: "mkdir://${paths.out_base}/log"
  output_dir: "mkdir://${paths.out_base}/results"
  model_dir: "mkdir://${paths.output_dir}/models/"
  model_path: "${paths.model_dir}/${train.model_name}"
  tboard_log_path: "mkdir://${paths.log_base}/tboard/${tag}"
  state_file_path: "${paths.model_dir}/${train.state_name}.json"
  label_path: "/code/pkgs/partnet/labels/chair.txt"
  eval_path: "mkdir://${paths.output_dir}/eval_images/"
  model_weights: null
#  model_weights: "${paths.out_base}/init-models/mask_rcnn_coco.h5"
